[package]
name = "domain"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
html-escape = "0.2.13"
reqwest = "0.12.4"
scraper = "0.19.0"
serde = "1.0.198"
serde_derive = "1.0.198"
serde_json = "1.0.116"
urlencoding = "2.1.3"
